var N = null;var sourcesIndex = {};
sourcesIndex["frunk"] = {"name":"","files":["lib.rs","monoid.rs","semigroup.rs","validated.rs"]};
sourcesIndex["frunk_core"] = {"name":"","files":["coproduct.rs","generic.rs","hlist.rs","indices.rs","labelled.rs","lib.rs","macros.rs","path.rs","traits.rs","tuples.rs"]};
sourcesIndex["frunk_derives"] = {"name":"","files":["derive_generic.rs","derive_labelled_generic.rs","lib.rs"]};
sourcesIndex["frunk_proc_macro_helpers"] = {"name":"","files":["lib.rs"]};
sourcesIndex["frunk_proc_macros"] = {"name":"","files":["lib.rs"]};
sourcesIndex["frunk_proc_macros_impl"] = {"name":"","files":["lib.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","files":["fallback.rs","lib.rs","strnom.rs","wrapper.rs"]};
sourcesIndex["proc_macro_hack"] = {"name":"","files":["lib.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","files":["gen_helper.rs"]}],"files":["attr.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","ty.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
createSourceSidebar();
