#!/usr/bin/env bash

if ! [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "Running benchmarks";
    travis-cargo --only nightly bench > benches-variable;
    git fetch;
    git checkout master;
    travis-cargo --only nightly bench > benches-control;
    travis-cargo --only nightly benchcmp benches-control benches-variable;
    exit 0;
fi