#!/usr/bin/env bash

if [ "${TRAVIS_PULL_REQUEST_BRANCH:-TRAVIS_BRANCH}" != "master" ] && [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
  rustup run nightly cargo bench > benches-variable;
  git fetch;
  git checkout master;
  rustup run nightly cargo bench > benches-control;
  rustup run nightly cargo benchcmp benches-control benches-variable;
fi